project:
  type: website

website:
  page-navigation: true
  title: "U.S. Greenhouse Gas Center Documentation"
  site-url: "https://us-ghg-center.github.io/ghgc-docs"
  repo-url: https://github.com/us-ghg-center/ghgc-docs
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By U.S. GHGC, 2022-2023"

  sidebar:
    logo: "Logo/ghg-logo.svg"
    pinned: true
    align: center
    tools:
      # - icon: info-circle
      #   href: https://www.earthdata.nasa.gov/esds/veda
      #   text: "earthdata.nasa.gov/esds/veda"
      - icon: github
        href: https://github.com/us-ghg-center/ghgc-docs
        text: "Repository home"
      # - icon: binoculars
      #   href: https://earthdata.nasa.gov/dashboard
      #   text: "VEDA Dashboard"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: User Services
        contents:
          - services/apis.qmd
          - services/jupyterhub.qmd
      - section: Data Usage Notebooks
        contents:
          - user_data_notebooks/casagfed-carbonflux-monthgrid-v3_User_Notebook.ipynb
          - user_data_notebooks/eccodarwin-co2flux-monthgrid-v5_User_Notebook.ipynb
          - user_data_notebooks/emit-ch4plume-v1_User_Notebook.ipynb
          - user_data_notebooks/epa-ch4emission-grid-v2express_User_Notebook.ipynb
          - user_data_notebooks/gosat-based-ch4budget-yeargrid-v1_User_Notebook.ipynb.ipynb
          - user_data_notebooks/lpjwsl-wetlandch4-grid-v1_User_Notebook.ipynb
          - user_data_notebooks/oco2-based-co2budget-yeargrid-v1_User_Notebook.ipynb
          - user_data_notebooks/oco2geos-co2-daygrid-v10r_User_Notebook.ipynb
          - user_data_notebooks/odiac-ffco2-monthgrid-v2022_User_Notebook.ipynb
          - user_data_notebooks/tm54dvar-ch4flux-monthgrid-v1_User_Notebook.ipynb
      - section: Data Transformation Documentation
        contents:
          - cog_transformation/casagfed-carbonflux-monthgrid-v3.ipynb
          - cog_transformation/ceos-ch4budget-yeargrid-v1.ipynb
          - cog_transformation/oco2-based-co2budget-yeargrid-v1.ipynb
          - cog_transformation/eccodarwin-co2flux-monthgrid-v5.ipynb
          - cog_transformation/emit-ch4plume-v1.ipynb
          - cog_transformation/epa-ch4emission-grid-v2express.ipynb
          - cog_transformation/epa-ch4emission-monthgrid-v2.ipynb
          - cog_transformation/gosat-based-ch4budget-yeargrid-v1.ipynb
          - cog_transformation/lpjwsl-wetlandch4-daygrid-v1.ipynb
          - cog_transformation/lpjwsl-wetlandch4-monthgrid-v1.ipynb
          - cog_transformation/oco2geos-co2-daygrid-v10r.ipynb
          - cog_transformation/odiac-ffco2-monthgrid-v2022.ipynb
          - cog_transformation/sedac-popdensity-yeargrid5yr-v4.11.ipynb
          - cog_transformation/tm54dvar-ch4flux-monthgrid-v1.ipynb
      - section: Processing and Verification Reports
        contents:
          - processing_and_verification_reports/casagfed-carbonflux-monthgrid-v3_Processing and Verification Report.qmd
          - processing_and_verification_reports/ceos-ch4budget-yeargrid-v1_Processing and Verification Report.qmd
          - processing_and_verification_reports/ceos-co2budget-yeargrid-v1_Processing and Verification Report.qmd
      - section: Data Workflow
        contents:
          - data_workflow/casagfed-carbonflux-monthgrid-v3_Data_Flow.qmd
format:
  html:
    theme:
      light: [flatly]
      dark: [darkly]
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
filters:
  - quarto
