project:
  type: website

website:
  page-navigation: true
  back-to-top-navigation: true
  title: "U.S. Greenhouse Gas Center Documentation"
  site-url: "https://us-ghg-center.github.io/ghgc-docs"
  repo-url: https://github.com/us-ghg-center/ghgc-docs
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By US GHG Center, 2022-2023"

  sidebar:
    logo: "logo/ghgc-logo-light.svg"
    pinned: true
    align: center
    tools:
      # - icon: info-circle
      #   href: https://www.earthdata.nasa.gov/esds/veda
      #   text: "earthdata.nasa.gov/esds/veda"
      - icon: globe-americas
        href: https://earth.gov/ghgcenter
        text: "US GHG Center Website"
      - icon: github
        href: https://github.com/us-ghg-center/ghgc-docs
        text: "Repository home"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - section: User Services
        contents:
          - services/apis.qmd
          - services/jupyterhub.qmd
      - href: datausage.qmd
        text: Data Usage Notebooks   
      - href: datatransformation.qmd
        text: Data Transformation Documentation 
      - href: processingreport.qmd
        text: Processing and Verification Reports   
      - href: workflow.qmd
        text: Data Workflow
      - href: advanceduser.qmd
        text: Advanced User Notebooks
format:
  html:
    grid:
      sidebar-width: 25vw
      body-width: 900px
    theme:
      light: [flatly]
      dark: [darkly]
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
filters:
  - quarto
