project:
  type: website

website:
  page-navigation: true
  title: "U.S. Greenhouse Gas Center Documentation"
  site-url: "https://us-ghg-center.github.io/ghgc-docs"
  repo-url: https://github.com/us-ghg-center/ghgc-docs
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By U.S. GHGC, 2022-2023"

  sidebar:
    logo: "Logo/ghg-logo.svg"
    pinned: true
    align: center
    tools:
      # - icon: info-circle
      #   href: https://www.earthdata.nasa.gov/esds/veda
      #   text: "earthdata.nasa.gov/esds/veda"
      - icon: github
        href: https://github.com/us-ghg-center/ghgc-docs
        text: "Repository home"
      # - icon: binoculars
      #   href: https://earthdata.nasa.gov/dashboard
      #   text: "VEDA Dashboard"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - section: cog_transformation/index.qmd
        contents:
          - cog_transformation/casagfed-carbonflux-monthgrid-v3_Transformation_Code.qmd
          - cog_transformation/ceos-co2budget-yeargrid-v1_Transformation_Code.qmd
          - cog_transformation/emit-ch4plume-v1_Transformation_Code.qmd
          - cog_transformation/epa-ch4emission-grid-v2_Transformation_Code.qmd
          - cog_transformation/epa-ch4emission-monthgrid-v2_Transformation_Code.qmd
          - cog_transformation/lpjwsl-wetlandch4-daygrid-v1_Transformation_Code.qmd
          - cog_transformation/lpjwsl-wetlandch4-monthgrid-v1_Transformation_Code.qmd
          - cog_transformation/odiac-ffco2-monthgrid-v2022_Transformation_Code.qmd
          - cog_transformation/sedac-popdensity-yeargrid5yr-v4.11_Transformation_Code.qmd      
      - section: user_data_notebooks/index.qmd
        contents:
          - user_data_notebooks/casagfed-carbonflux-monthgrid-v3_User_Notebook.ipynb
          - user_data_notebooks/ceos-co2budget-yeargrid-v1_User_Notebook.ipynb
          - user_data_notebooks/emit-ch4plume-v1_User_Notebook.ipynb
          - user_data_notebooks/epa-ch4emission-grid-v2_User_Notebook.ipynb
          - user_data_notebooks/lpjwsl-wetlandch4-grid-v1_User_Notebook.ipynb
          - user_data_notebooks/odiac-ffco2-monthgrid-v2022_User_Notebook.ipynb
          - user_data_notebooks/sedac-popdensity-yeargrid5yr-v4.11_User_Notebook.ipynb
      - section: processing_and_verification_reports/index.qmd
        contents:
          - processing_and_verification_reports/casagfed-carbonflux-monthgrid-v3_Processing and Verification Report.qmd
          - processing_and_verification_reports/lpjwsl-wetlandch4-grid-v1_Processing and Verification Report.pdf
          - processing_and_verification_reports/oco2geos-co2-daygrid-v10r_Processing and Verification Report.pdf
          - processing_and_verification_reports/odiac-ffco2-monthgrid-v2022_Processing and Verification Report.pdf
          - processing_and_verification_reports/sedac-popdensity-yeargrid5yr-v4.11_Processing and Verification Report.pdf
      - section: data_workflow/index.qmd
        contents:
          - data_workflow/casagfed-carbonflux-monthgrid-v3_Data_Flow.qmd
          - data_workflow/ceos-ch4budget-yeargrid-v1_Data_Flow.qmd
          - data_workflow/ceos-co2budget-yeargrid-v1_Data_Flow.qmd
format:
  html:
    theme:
      light: [flatly]
      dark: [darkly]
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
filters:
  - quarto
